# This workflow alerts and then closes the stale issues after specific time
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale

name: 'Close inactive issues'
on:
  workflow_dispatch:
  schedule:
    - cron: "30 1 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Awaiting response issues
        uses: actions/stale@v5
        with:
          days-before-issue-stale: 0
          days-before-issue-close: 0
          stale-issue-label: "stale"
          # reason for closed the issue default value is not_planned
          close-issue-reason: completed
          only-labels: "stat:awaiting response from contributor"
          stale-issue-message: > 
            This issue is stale because it has been open for 14 days with no activity.
            It will be closed if no further activity occurs. Thank you.
          close-issue-message: >
            This issue was closed because it has been inactive for 28 days.
            Please reopen if you'd like to work on this further.
          days-before-pr-stale: 14
          days-before-pr-close: 14
          stale-pr-message: "This PR is stale because it has been open for 14 days with no activity. It will be closed if no further activity occurs. Thank you."
          close-pr-message: "This PR was closed because it has been inactive for 28 days. Please reopen if you'd like to work on this further."
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      # - name: Contribution issues
      #   uses: actions/stale@v5
      #   with:
      #     days-before-issue-stale: 180
      #     days-before-issue-close: 365
      #     stale-issue-label: "stale"
      #     # reason for closed the issue default value is not_planned
      #     close-issue-reason: not_planned
      #     any-of-labels: "stat:contributions welcome,good first issue"
      #     stale-issue-message: > 
      #       This issue is stale because it has been open for 180 days with no activity.
      #       It will be closed if no further activity occurs. Thank you.
      #     close-issue-message: >
      #       This issue was closed because it has been inactive for more than 1 year.
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          script: |
            const script = require('./\.github/workflows/scripts/issue-pr-closed.js')
            script({github, context})
      




# name: 'Stale and Close issues'
# on:
#   workflow_dispatch:
#  issue_comment:
#    types:
#      - created
    
# permissions:
#   contents: read
#   issues: write
#   pull-requests: write

# jobs:
#   stale:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/stale@v7
#         with:
          
#           # close-as-complete: true 
#           close-issue-reason: completed
         
         
#           # comment on issues if not active for more then 14 days.
#           stale-issue-message: 'This issue has been automatically marked as stale because it has no recent activity. It will be closed if no further activity occurs. Thank you.'
        
#           #comment on issues if stale for more then 14 days. 
#           close-issue-message: "Closing as stale. Please reopen if you'd like to work on this further"
              
#           # Number of days of inactivity before a stale issue is closed
#           days-before-issue-close: 0
       
#           # Number of days of inactivity before an issue Request becomes stale
#           days-before-issue-stale: 0
         
#           exempt-issue-labels: 'override stale'
 
        

#           #Check for label to stale or close the issue/PR
#           any-of-labels: 'stat:awaiting response'
#           labels-to-remove-when-unstale: 'stale,stalled,stat:awaiting response'
         
#           #override stale to stalled for issue
#           stale-issue-label: 'stale'
#       - uses: actions/checkout@v3
#       - uses: actions/github-script@v6
#         with:
#           script: |
#             const script = require('./\.github/workflows/scripts/stale_csat.js')
#             script({github, context})
